### ISSUE TITLE
Does not compile out of the box for me

### ISSUE THREAD

**Issue by uson1x** [DarkHorseComics/DHAppleReceiptParser#2]
So I just tried to drop it in using CocoaPods, but I'm getting a bunch of linker errors, like these:

```
Undefined symbols for architecture armv7:
  "_RSA_private_decrypt", referenced from:
      _pkey_rsa_decrypt in libPods.a(rsa_pmeth.o)
  "_RSA_public_encrypt", referenced from:
      _pkey_rsa_encrypt in libPods.a(rsa_pmeth.o)
  "_RSA_size", referenced from:
      _RSA_sign in libPods.a(rsa_sign.o)
      _int_rsa_verify in libPods.a(rsa_sign.o)
      _int_rsa_size in libPods.a(rsa_ameth.o)
      _pkey_rsa_sign in libPods.a(rsa_pmeth.o)
      _RSA_verify_PKCS1_PSS_mgf1 in libPods.a(rsa_pss.o)
      _RSA_padding_add_PKCS1_PSS_mgf1 in libPods.a(rsa_pss.o)
      _RSA_sign_ASN1_OCTET_STRING in libPods.a(rsa_saos.o)
```

I believe they are all related to OpenSSL and to confirm, OpenSSL was "successfully" installed via CocoaPods too (v 1.0.1).

Am I doing something wrong here and it works fine out of the box for you? Maybe there are some hidden steps I'm not aware of?

**Comment by uson1x** [comment]
I was able to compile it in the end by manually including this library into the project: https://github.com/st3fan/ios-openssl. So again, the problem seems to be in OpenSSL pod, not yours, but I will leave this opened just to let you know that there is this issue. At least it's there for me.

**Comment by sealgair** [comment]
Thanks for pointing this out -- I had the same problem getting back to this today.  I've taken out the dependency on the OpenSSL cocoapod, and added the openssl libraries directly to this one -- let me know whether that helps.
